### PR TITLE
Config file reader genv

### PR DESCRIPTION
**Pull request by gordon-cheung**
This change is [Reviewable](https://reviewable.io/reviews/ucsolarcarteam/delta-onboard-media-control/55)

### CODE REVIEW

**Comment by bseto** [comment]
Hi Gordon. Please look at the test/ directory and add your test in there.

**Comment by bseto** [comment]
Hi Gordon. You have some tests that failed. Can you fix them?

**Comment by gordon-cheung** [comment]
getString test has failed, because it returns a string that is uppercase, when hashing the value for a string it should keep the string in its original (unaltered form), this will be fixed soon.

**Comment by bseto** [comment]
The tests work now. However, I feel like this should probably be made into a singleton that way, the .ini file only needs to be read once. Henry is the best!

**Comment by henrytran28** [comment]
I'll try to make this a singleton. Also should we move this to the EpsilonGEN or just finish this up here?

**Pull request closed without merging**
