### PR TITLE
Linux mint installer stability

### PR DESCRIPTION
**Pull request by ExtraGravity**
Made some changes on top of yours Byron. This install script will work on my computer Linux Mint. I'm still encountering a couple problems.

`sudo make` will finish compiling the backup camera, but running it will cause a segmentation fault before anything else.

I also cannot remove the downloaded files and unzipped folders in the install script.

I added a trap so even if compilation fails, the script will still attempt to remove the files. I also added wiring pi to the install script, because a clean install of linux mint requires wiringPi for the make file to compile due to the flag `-lwiringPi`

### CODE REVIEW

**Comment by bseto** [comment]
The segfault is because of the music not being in /home/Music.
If the segfault happens a little later, its because you didn't run sudo ./BackupCamera (Program needs access to /home/)

**Comment by bseto** [comment]
Looks pretty good though. I will test it out soon (The trap) and what do you mean by "I also cannot remove the downloaded files and unzipped folders in the install script."?

Note: The fix to the segfault will be done in two ways (We will do both). Add 1-2 songs in the "SongLibrary" folder included in the repository, and change gordon's music bar to not initialize if musicPlayer is not initialized

**Comment by ExtraGravity** [comment]
Alternatively, the program could end purposefully with an error message instead of a seg fault.

At the end of the install script, it does enter the trap to run the commands, but gives me errors instead of removing those directories/files.

**Comment by ExtraGravity** [comment]
The script has some `cd` commands, so depending on where the script ends, it will be in a different directory. So I changed the `rm` instructions to be absolute paths, I still get this error with the directories though: 

```
Cleaning up...
rm: cannot remove ‘/home/enoch/ext/SolarCar/Schulich-Delta-OnBoard-Media-Control/Installer/SDL2_image-2.0.0’: Directory not empty
rm: cannot remove ‘/home/enoch/ext/SolarCar/Schulich-Delta-OnBoard-Media-Control/Installer/SDL2-2.0.3/build’: Directory not empty
rm: cannot remove ‘/home/enoch/ext/SolarCar/Schulich-Delta-OnBoard-Media-Control/Installer/SDL2_mixer-2.0.0/external/smpeg2-2.0.0’: Directory not empty
rm: cannot remove ‘/home/enoch/ext/SolarCar/Schulich-Delta-OnBoard-Media-Control/Installer/SDL2_mixer-2.0.0/Xcode/Frameworks/Ogg.framework/Versions/A/Resources’: Directory not empty
```

**Comment by bseto** [comment]
Somethings weird about your output. Normally it would give you the error on the directory you wanted to delete. Your first error seems legit: `
rm: cannot remove ‘/home/enoch/ext/SolarCar/Schulich-Delta-OnBoard-Media-Control/Installer/SDL2_image-2.0.0’: Directory not empty`

However, your other errors look wierd..
`rm: cannot remove ‘/home/enoch/ext/SolarCar/Schulich-Delta-OnBoard-Media-Control/Installer/SDL2_mixer-2.0.0/Xcode/Frameworks/Ogg.framework/Versions/A/Resources’: Directory not empty`

I would suggest trying what this guy says: http://stackoverflow.com/questions/790195/rm-fails-to-delete-files-by-wildcard-from-a-script-but-works-from-a-shell-promp

Solution was to change
`rm -rf $DIR/SDL2_image-2.0.0  || true`
to 
`rm -rf "$DIR"/SDL2_image-2.0.0  || true`

Let me know if that works!

**Comment by ExtraGravity** [comment]
So it did actually fix one error, this is the output now:

```
rm: cannot remove ‘/home/enoch/ext/SolarCar/Schulich-Delta-OnBoard-Media-Control/Installer/SDL2-2.0.3/src/video/cocoa’: Directory not empty
rm: cannot remove ‘/home/enoch/ext/SolarCar/Schulich-Delta-OnBoard-Media-Control/Installer/SDL2-2.0.3/src/video/uikit’: Directory not empty
rm: cannot remove ‘/home/enoch/ext/SolarCar/Schulich-Delta-OnBoard-Media-Control/Installer/SDL2_mixer-2.0.0/external/smpeg2-2.0.0’: Directory not empty
```

Does the removal work on your computer?

**Comment by bseto** [comment]
Tested, removal works on my computer. Merging

**Pull request merged**
