### PR TITLE
Supporting rendering

### LINKED ISSUE #29: Should check for Hardware Accelerated or Software rendering.
I re-installed linux on my laptop and my graphics card no longer is recognized. I will fix this later (hopefully), but without any hardware accelerated rendering, our program will not work.

So if someone has a computer without a graphics card, or is using a VM, the backup camera will not work. 

The problem is because `renderer = SDL_CreateRenderer(` is created with the flag  `SDL_RENDERER_ACCELERATED`.

If we want it to work with VM's, we need the `SDL_RENDERER_SOFTWARE` flag instead.

I'd like our code to somehow check if the host computer can use hardware accelerated rendering. If not, then it should use the software renderer.

### PR DESCRIPTION
**Pull request by bseto**
Fixes #29

### CODE REVIEW

**Comment by bseto** [comment]
@enochtsang, please test this on a VM. 

Use the Installer scripts and then run the BackupCamera. Should be super laggy but it runs. You also probably have to set 3D rendering or something on your Virtual Box

**Comment by ExtraGravity** [comment]
So what is the purpose of this pull request? Is it for VMs?

**Comment by bseto** [comment]
Yes and no. 

Sometime's when you install Linux, Linux might not be able to use your graphics card as a hardware renderer. So on Saturday Nov 21, we tried to get Bryson's laptop to run our program, however, it didn't work because SDL could not find a hardware renderer meaning his computer didn't have support for hardware rendering. 

This pull request is just to make the program more robust so it can run on VM's and computers that don't have hardware rendering enabled. 

**Note** that hardware rendering isn't just from a graphics card. Gordon has hardware rendering enabled on his laptop even though his laptop is only integrated. I'm pretty sure you just have to play around with drivers and stuff until you get hardware rendering enabled.

**Comment by ExtraGravity** [comment]
Makes sense Stage 1 of pull request is good
Stage 2 code structure looks fine as well (but you would know better)
Stage 3 : bugs and glitches

**Comment by bseto** [comment]
What bugs and glitches do you encounter?

**Comment by ExtraGravity** [comment]
I wanted to compile and run on my side first. Looks good! 
Stage 3 Looks good
Stage 4 Coding Style

**Comment by ExtraGravity** [comment]
Looks beautiful merging.

**Pull request merged**
